# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install: 
  R -e 'install.packages('pdftools')
  R -e 'install.packages('antiword')
after_success:
        - Rscript -e 'covr::codecov()'
